Dev: &dev_anchor
  Discord:
    Token: dev-token

  Db:
    Host: 127.0.0.1
    Port: 5432
    Database: sbu-bot-db
    Username: postgres
    Password: postgres

# use dev until deployed
Prod: *dev_anchor